# Generated by Django 4.2.3 on 2023-07-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
